<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwJ5eo6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwJ5eo6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFwJ5eo6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFwJ5eo6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFwJ5eo6\App_KernelDevDebugContainer([
    'container.build_hash' => 'FwJ5eo6',
    'container.build_id' => '2abd885f',
    'container.build_time' => 1714421598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwJ5eo6');
