<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE85Bzdz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE85Bzdz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE85Bzdz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE85Bzdz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE85Bzdz\App_KernelDevDebugContainer([
    'container.build_hash' => 'E85Bzdz',
    'container.build_id' => 'eb55e764',
    'container.build_time' => 1714604737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE85Bzdz');
